### ISSUE TITLE
Infinite loop when no input file is given as argument instead of reading standard input

### ISSUE THREAD

**Issue by CratesDeThebes** [ra3xdh/qucsator_rf#24]
Documentation states that the executable defaults to read `stdin` and with option -i it uses file as input netlist.
Currently, when running the executable without option, an infinite loop starts and can only be interrupted with CTRL-C keys.

This behaviour is due to the code in `ucs.cpp`, when no argument is found, a first step opens the input file and searches for `--path` and `--module` and then closes the input file. This step should wrapped in a `if (infile != NULL) {...}` block.

**Comment by ra3xdh** [comment]
Yes, I confirm this bug. To be honestly, I never used the reading of the `STDIN` with qucsator and didn't test this. I am not sure when it became broken. If you are using qucsator inside some script, you may specify the input file with `-i` option. I will provide a fix in the next release.

**Comment by ra3xdh** [comment]
Fixed by #29
